server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 改为update，避免每次重建表
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        # 解决中文乱码
        connection:
          characterEncoding: utf8
          useUnicode: true
        
# 日志配置
logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    root: INFO
    com.example.hrms: DEBUG

# JWT配置
jwt:
  secret: hrms_jwt_secret_key_2025_very_long_and_secure_for_hs512_algorithm_minimum_512_bits_required_padding_to_ensure_sufficient_length
  expiration: 86400000  # 24小时

# 应用配置
app:
  init:
    test-data: true  # 开发环境设为true，生产环境设为false
    force: false
  jwt:
    secret: hrms_jwt_secret_key_2025_very_long_and_secure
    expiration: 86400  # 24小时（秒）
    token-prefix: "Bearer "
    token-header: "Authorization"
  upload:
    path: "./uploads/"
    allowed-types: 
      - jpg
      - jpeg
      - png
      - gif
      - pdf
      - doc
      - docx
      - xls
      - xlsx
    max-size: 10  # MB

# Swagger配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

# 文件上传配置
spring.servlet.multipart:
  max-file-size: 10MB
  max-request-size: 100MB